# Generated by Django 3.1 on 2020-08-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200822_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='user12',
        ),
    ]
